### ISSUE TITLE
node ace `serve` and `invoke` are not a registered command 

### ISSUE THREAD

**Issue by nasrat-v** [reg2005/adonis5-swagger#11]
## Package version
```
"@adonisjs/ace": "^5.0.8",
"adonis5-swagger": "^1.2.1"
```

## Node.js and npm version
```
node: v14.7.0
npm: 6.14.7
```

## Sample Code (to reproduce the issue)
```
node ace serve --watch
node ace invoke adonis5-swagger
```

The command serve and invoke are not recognized by `ace`.
Is this related to this package ?

**Comment by VladyslavP98** [comment]
serve and invoke are provided by https://github.com/adonisjs/assembler. Did you install this package ?

**Comment by nasrat-v** [comment]
I did but that doesn't fix it.  
Do I need to register the assembler package as an aceProviders in my app.js ?

**Comment by VladyslavP98** [comment]
I'm not sure how adonis register assembler commands, but i didn't register any adonis commands. You should generate new package using adonis-cli or you could look on example of adonis project https://github.com/marcelodosreis/Shingeki-No-Kyojin-API

**Comment by VladyslavP98** [comment]
Did you solve your problem ? Can I close this issue ?

**Comment by nasrat-v** [comment]
I didn't solve the issue. I think I need a fresh install of adonis.
I'll close the issue. Thanks for your time.
