### ISSUE TITLE
this.container.use is not a function

### ISSUE THREAD

**Issue by devotox** [reg2005/adonis5-swagger#12]
## Package version
Adonis Core Version: 5.1.4
Adonis5 Swagger Version: 1.2.1

## Node.js and npm version
Node Version: 14.15.3
NPM Version: 6.14.9
Yarn Version: 1.22.10

## Sample Code (to reproduce the issue)
Update adonis to the latest version

## BONUS (a sample repo to reproduce the issue)
Just any newly created adonis App

```
TypeError: this.container.use is not a function


1 SwaggerProvider.initSwaggerRoutes
  /Users/devonte/Documents/GetCircuit/circuit-engine/node_modules/adonis5-swagger/build/providers/SwaggerProvider.js:14

2 SwaggerProvider.boot
  /Users/devonte/Documents/GetCircuit/circuit-engine/node_modules/adonis5-swagger/build/providers/SwaggerProvider.js:10

3 Registrar.boot
  /Users/devonte/Documents/GetCircuit/circuit-engine/node_modules/@adonisjs/fold/build/src/Registrar/index.js:116

4 anonymous
  /Users/devonte/Documents/GetCircuit/circuit-engine/node_modules/@adonisjs/application/build/src/Application.js:543

5 Profiler.profileAsync
  /Users/devonte/Documents/GetCircuit/circuit-engine/node_modules/@adonisjs/profiler/build/src/Profiler/AbstractProfiler.js:20

6 Application.bootProviders
  /Users/devonte/Documents/GetCircuit/circuit-engine/node_modules/@adonisjs/application/build/src/Application.js:541

7 HttpServer.wire
  /Users/devonte/Documents/GetCircuit/circuit-engine/node_modules/@adonisjs/core/build/src/Ignitor/HttpServer/index.js:56

8 HttpServer.start
  /Users/devonte/Documents/GetCircuit/circuit-engine/node_modules/@adonisjs/core/build/src/Ignitor/HttpServer/index.js:146

```

**Comment by VladyslavP98** [comment]
I got it, I will check it as soon as I can. I suppose, that adonis/fold has breaking changes in last versions.

**Comment by devotox** [comment]
Yup a lot of things were broken. I have been trying to figure out what changes are needed in your repo but do not know enough about Adonis Plugins

**Comment by VladyslavP98** [comment]
Could you try to `npm i git://github.com/reg2005/adonis5-swagger.git#adonis_update`
I made some updates, if this help you, we will publish new package version

**Comment by devotox** [comment]
@VladyslavParashchenko that worked!

I see where my issue was. When trying to fix the code I was using

```
        const config = this.container.resolveBinding('Adonis/Core/Config');
        const router = this.container.resolveBinding('Adonis/Core/Route');
```

instead of the updated

```
        const config = this.app.container.resolveBinding('Adonis/Core/Config');
        const router = this.app.container.resolveBinding('Adonis/Core/Route');
```

**Comment by VladyslavP98** [comment]
Any Adonis Provider has flag needsApplication in provider. Adonis provider loader set to provider constructor adonis app or only container depends on this flag. I think that adonis changed default behavior for this flag, and adonis swagger provider received whole app object, instead of only container. I don't know details know, I will check it in my free time. 
We will update package, after testing on our apps with more old adonis versions.

**Comment by devotox** [comment]
Can you send me a link to how to create Adonis Providers so I can be well versed in this and next time be able to help you update the actual codebase and just send a PR

**Comment by VladyslavP98** [comment]
As I know adonis haven't any docs, how to develop packages. I usually read official packages source core, for getting knowledge how adonis is working.

**Comment by devotox** [comment]
Any update on when your PR will be merged?

**Comment by VladyslavP98** [comment]
I can't deploy new package version to npm.  Account owner for this package hasn't asnwered me yet.

**Comment by reg2005** [comment]
@devotox [PR](https://github.com/reg2005/adonis5-swagger/pull/13) was merged.
