### ISSUE TITLE
Authorize button on ui 

### ISSUE THREAD

**Issue by firdausalif** [reg2005/adonis5-swagger#17]
Why the authorization button not showing on ui? any good example?

swagger.json
```json
{
  "openapi":"3.0.0",
  "info":{
    "title":"Simbyo Api",
    "version":"1.0.0",
    "description":"XX!"
  },
  "paths":{},
  "components":{
    "securitySchemes":{
      "bearerAuth":{
        "type": "http",
        "scheme": "bearer",
        "bearerFormat": "JWT"
      }
    }
  },
  "tags":[]
}
```

auth.yml
```yml
/api/auth/logout:
  post:
    summary: Logout
    security:
      - bearerAuth: []
    responses:
      200:
        description: Success
      422:
        description: Failed
      401:
        description: Unauthorized
```

**Comment by VladyslavP98** [comment]
Could you describe you problem with more details ? I've tried to reproduce and I haven't any issue.
![image](https://user-images.githubusercontent.com/18124826/122684663-64a7e800-d20f-11eb-9782-7ce96e0eb478.png)

**Comment by firdausalif** [comment]
im using .yml to create the path, but my screen look like this, no button Authorize

![image](https://user-images.githubusercontent.com/24265986/122695610-14f70a00-d26b-11eb-922b-2af870fb01ba.png)


![image](https://user-images.githubusercontent.com/24265986/122695416-7e2a4d80-d26a-11eb-8ab3-0a7871b50ff1.png)

**Comment by VladyslavParashchenko** [comment]
Copy `swagger.json` options to `config/swagger.json` 
export default {
  uiEnabled: true, //disable or enable swaggerUi route
  uiUrl: 'docs', // url path to swaggerUI
  specEnabled: true, //disable or enable swagger.json route
  specUrl: '/swagger.json',

  middleware: [], // middlewares array, for protect your swagger docs and spec endpoints

  options: {
    definition: {
      openapi: '3.0.0',
      info: {
        title: 'Simbyo Api',
        version: '1.0.0',
        description: 'XX!',
      },
      paths: {},
      components: {
        securitySchemes: {
          bearerAuth: {
            type: 'http',
            scheme: 'bearer',
            bearerFormat: 'JWT',
          },
        },
      },
      tags: [],
    },

    apis: ['app/**/*.ts', 'docs/**/*.yml', 'start/routes.ts'],
    basePath: '/',
  },
  mode: process.env.NODE_ENV === 'production' ? 'PRODUCTION' : 'RUNTIME',
  specFilePath: 'docs/swagger.json'
} as SwaggerConfig

**Comment by VladyslavP98** [comment]
You should copy content of your `swagger.json` to `config/swagger.ts`. 
```export default {
  uiEnabled: true,
  uiUrl: 'docs', 
  specEnabled: true, 
  specUrl: '/swagger.json',

  middleware: [], 

  options: {
    definition: {
      openapi: '3.0.0',
      info: {
        title: 'Simbyo Api',
        version: '1.0.0',
        description: 'XX!',
      },
      paths: {},
      components: {
        securitySchemes: {
          bearerAuth: {
            type: 'http',
            scheme: 'bearer',
            bearerFormat: 'JWT',
          },
        },
      },
      tags: [],
    },

    apis: ['app/**/*.ts', 'docs/**/*.yml', 'start/routes.ts'],
    basePath: '/',
  },
  mode: 'RUNTIME',
  specFilePath: 'docs/swagger.json'
}
```
You will find more details how use swagger by this link. Swagger.json is authogenerated file, which can be generated via command `node ace swagger:generate`
[Swagger modes](https://github.com/reg2005/adonis5-swagger#swagger-modes)
[Production using](https://github.com/reg2005/adonis5-swagger#production-using)

**Comment by firdausalif** [comment]
> You should copy content of your `swagger.json` to `config/swagger.ts`.
> 
> ```
>   uiEnabled: true,
>   uiUrl: 'docs', 
>   specEnabled: true, 
>   specUrl: '/swagger.json',
> 
>   middleware: [], 
> 
>   options: {
>     definition: {
>       openapi: '3.0.0',
>       info: {
>         title: 'Simbyo Api',
>         version: '1.0.0',
>         description: 'XX!',
>       },
>       paths: {},
>       components: {
>         securitySchemes: {
>           bearerAuth: {
>             type: 'http',
>             scheme: 'bearer',
>             bearerFormat: 'JWT',
>           },
>         },
>       },
>       tags: [],
>     },
> 
>     apis: ['app/**/*.ts', 'docs/**/*.yml', 'start/routes.ts'],
>     basePath: '/',
>   },
>   mode: 'RUNTIME',
>   specFilePath: 'docs/swagger.json'
> }
> ```
> 
> You will find more details how use swagger by this link. Swagger.json is authogenerated file, which can be generated via command `node ace swagger:generate`
> [Swagger modes](https://github.com/reg2005/adonis5-swagger#swagger-modes)
> [Production using](https://github.com/reg2005/adonis5-swagger#production-using)

Thanks its solve now
![image](https://user-images.githubusercontent.com/24265986/123382856-a1336500-d5bc-11eb-988f-0278a7535d12.png)
