### ISSUE TITLE
update docs?

### ISSUE THREAD

**Issue by daniellizik** [reg2005/adonis5-swagger#29]
It took me a while to get setup as the docs lack a full example of the correct config to use

for development I had to console log through the source code to find why my config was not right, I ended up using this

```ts
// config/swagger.ts
import path from 'path';

export default {
  specEnabled: true,
  specUrl: path.resolve(__dirname, '..', 'docs', 'swagger.json'),
  specFilePath: path.resolve(__dirname, '..', 'docs', 'swagger.json'),
  uiEnabled: true,
  uiUrl: '/docs',
  options: {
    apis: ['docs/**/*.yml'],
    definition: {
      openapi: '3.0.0',
      info: {
        title: 'Hello World',
        version: '1.0.0'
      }
    }
  }
};
```

**Comment by VladyslavP98** [comment]
Hi, I'm not sure it is a bug. You have to follow next steps:
1. Build swagger config using command: `node ace swagger:generate`
2. Copy generated file to <build-dir>/docs/swagger.json
3. Add `mode: PRODUCTION` to your swagger config. When this mode enabled adonis streams file from FS by next path
 `join(this.app.appRoot,this.config.get('swagger.specFilePath'))`
