### ISSUE TITLE
.yml files in docs not working on production build

### ISSUE THREAD

**Issue by alexdonh** [reg2005/adonis5-swagger#3]
## Package version
[adonis5-swagger@1.0.5](https://www.npmjs.com/package/adonis5-swagger)

## Node.js and npm version
```
node --version
v12.19.0

npm --version
6.14.8
```

## Reproduce
1. Follow best practices to create .yml files in docs/swagger 
2. Compile for production `node ace build --production`
3. Copy docs over `cp docs build/docs`
4. Run production `node build/server.js`

## Expect
Docs can also be viewed in production build

## Actual
Swagger UI loaded but no specs.

**Comment by VladyslavP98** [comment]
We added [https://github.com/reg2005/adonis5-swagger/pull/4](Fix) to our package. Please update package and check is it fixed ?

**Comment by alexdonh** [comment]
@VladyslavParashchenko I did have a look into your pull request (which has been already merged). Correct me if I'm wrong but from what I can understand its only needed to change the path in `apis` in `swagger.ts` config file. 

However, even when I copy the whole `docs` folder into `build`, which should make the paths correct without changing config file, I still can't get it to work on production mode. 

Am I missing something?

~~Update:~~

~~I bump to tag v1.0.6 which already included your merge, still no luck...~~

~~What I did~~

~~1. `yarn upgrade`~~
~~2. Make sure adonis5-swagger is 1.0.6~~
~~3. `npm run build --production`~~
~~4. `node build/server.js`~~
~~5. Browse http://localhost:3333/docs => No operations defined in spec!~~

~~Update 2:~~

~~After upgrading to 1.0.6, even dev run not working! `node ace serve --watch` or `yarn start` and the development server no longer loads the .yml files in docs.~~

See comment below.

**Comment by VladyslavP98** [comment]
You shouldn't copy your docs to build dir, package expects that .yml files are near your typescript code.

**Comment by alexdonh** [comment]
Thanks for the quick response! I updated my comment above. please check.

**Comment by VladyslavP98** [comment]
Could you show your project  files structure and swagger config ?

**Comment by alexdonh** [comment]
Yeahhhh thanks for reminding. I was stupid enough not updating the config file. It works now.

However... IMO If I want users to see the documentation, I would just include it in the build folder. It's easier for deployment (you only need to package everything inside that `build` folder).

I realized that we can achieve it without changing much.

1. Update `apis` in `swagger.ts` config: remove the parent relative path. E.g. 

```
    apis: [
      'app/**/*.ts',
      'docs/swagger/**/*.yml',
      'start/routes.ts'
    ],
```

2. In `.adonisrc.json`, add `docs` folder in `metaFiles`. E.g.

```
  "metaFiles": [
    ".env",
    ".adonisrc.json",
    "docs" // HERE
  ]
```

Then the `build` process will copy the docs into `build` for you.

It works with old v1.0.5 too
