### ISSUE TITLE
ENOENT: no such file or directory, open 'F:\server\htdocs\adonis_app\docs\swagger.json'

### ISSUE THREAD

**Issue by waseemchanna29** [reg2005/adonis5-swagger#33]
I have an issue with adonis 5 version, getting the following issue when running command **node ace swagger:generate**

ENOENT: no such file or directory, open 'F:\server\htdocs\adonis_app\docs\swagger.json'

**Comment by VladyslavP98** [comment]
Try to create `docs` dir inside root dir of your project and retun command

**Comment by VladyslavP98** [comment]
@waseemchanna29 is your issue was solved ?
