### ISSUE TITLE
adonis5-swagger SwaggerConfig don't working. Plase, change to my working config.

### ISSUE THREAD

**Issue by eldiyar-dev** [reg2005/adonis5-swagger#34]
**This your config don't wokring**
export default {
	// ... config options
	options: {
		definition: {
		openapi: '3.0.0',
		info: {
			title: 'Application with swagger docs',
			version: '1.0.0',
			description: 'My application with swagger docs'
		},
		components: {
			securitySchemes: {
			bearerAuth: {
				type: "http",
				scheme: "bearer",
				bearerFormat: "JWT"
			}
			}
		}
		}
	//... config options
	}
} as SwaggerConfig

**This my config wokring**

`export default {
	// ... config options
	options: {
		definition: {
      openapi: '3.0.0',
      info: {
        title: 'Application with swagger docs',
        version: '1.0.0',
        description: 'My application with swagger docs'
      },
      components: {
        securitySchemes: {
          bearerAuth: {
            type: "http",
            scheme: "bearer",
            bearerFormat: "JWT"
          }
        }
      }
		}
	//... config options
	}
} as SwaggerConfig`

**Comment by VladyslavP98** [comment]
Could you give more details, why config isn't working ?
