### ISSUE TITLE
Swagger defaults to pet-store json file after updating to v1.4.0

### ISSUE THREAD

**Issue by taist24** [reg2005/adonis5-swagger#35]
### Description

After updating to 1.4.0, The swagger doc use default example json file i.e. `https://petstore.swagger.io/v2/swagger.json`. I've to manually type in `/swagger.json` to navigate to my API doc.

I can confirm this works perfectly on v1.3.3 and not on v1.4.0.

## Package version
1.4.0

## Node.js and npm version
Node: 16.13.1
NPM: 8.1.2

**Comment by navaismo** [comment]
Same issue here. Basically is the file **swagger-initializer.js**  in swagger-ui-dist package. You can make 2 works around in the mean time the dev fix it:

1) open the file swagger-initializer.js and edit the line: url: "https://petstore.swagger.io/v2/swagger.json" to url: "/swagger.json"

or 

2) Add these lines in the file  **SwaggerController.js** from adonis5-swagger after line 56:
```js
if (fileName.includes('initializer')) {
            //replace default host from swagger-initializer.js
            data = data.replace('https://petstore.swagger.io/v2/swagger.json', this.config.get('swagger.specUrl'));
        }

```

**Comment by VladyslavP98** [comment]
UI dist moved initializer from html to initializer.

Could you test my fix please ? Install via branch 
package.json:
`  "adonis5-swagger": "reg2005/adonis5-swagger.git#fix-swagger-init"`

**Comment by PieterLetsdial** [comment]
I can confirm branch reg2005/adonis5-swagger.git#fix-swagger-init does resolve the issue

**Comment by taist24** [comment]
> UI dist moved initializer from html to initializer.
> Could you test my fix please ? Install via branch
package.json:
"adonis5-swagger": "reg2005/adonis5-swagger.git#fix-swagger-init"

How to test this? I've simply added `"adonis5-swagger": "reg2005/adonis5-swagger.git#fix-swagger-init"` inside my package.json. However, it seems to be throwing error.

**Comment by VladyslavP98** [comment]
@taist24 reinstall packages and check

**Comment by VladyslavP98** [comment]
@reg2005 Could you merge this [PR](https://github.com/reg2005/adonis5-swagger/pull/36) and publish fix version ?

**Comment by reg2005** [comment]
Ok. New version 1.4.1 is ready
