### ISSUE TITLE
Not Found /swagger.json

### ISSUE THREAD

**Issue by Aecil** [reg2005/adonis5-swagger#39]
Hello, my problem rises when a try to deploy the api to render, when i visit the /docs
i get Fetch error Not Found /swagger.json.
I follow the readme.md but i don't know what else to do.

## Package version
  "adonis5-swagger": "^1.4.1"

## Node.js and npm version
16

## Sample Code (to reproduce the issue)
export default {
  uiEnabled: true, //disable or enable swaggerUi route
  uiUrl: 'docs', // url path to swaggerUI
  specEnabled: true, //disable or enable swagger.json route
  specUrl: '/swagger.json',

  middleware: [], // middlewares array, for protect your swagger docs and spec endpoints

**Comment by VladyslavP98** [comment]
Hi, sorry for the late response.  
You have to prebuilt swagger.json for production use. I suggest it because it will work quicker compared to the usual mode.
Please look details [here](https://github.com/reg2005/adonis5-swagger#production-using)

**Comment by Aecil** [comment]
Thanks so much for the help. --Enviado desde mi teléfono Android con GMX Mail. Por favor, disculpe mi brevedad.El 3/3/23, 9:21 AM Vladyslav Parashchenko ***@***.***> escribió:

   
  Hi, sorry for the late response. You have to prebuilt swagger.json for production use. I suggest it because it will work quicker compared to the usual mode. Please look details here
