### ISSUE TITLE
Unwanted redirection

### ISSUE THREAD

**Issue by assaad97** [reg2005/adonis5-swagger#40]
Hello, i using adonisJs v5 to implement a rest api, and im using adonis5-swagger v1.4.1, and the issue that i have is whenever i try to access ```API_URL/docs``` it redirects me to another page, is there any way to prevent this redirection or to have an option to disable it, since it can be quite painful if i have a reverse proxy infront.

here is my swagger config :
```
export default {
	uiEnabled: true, //disable or enable swaggerUi route
	uiUrl: '/docs', // url path to swaggerUI
	specEnabled: true, //disable or enable swagger.json route
	specUrl: '/swagger.json',
	middleware: [], // middlewares array, for protect your swagger docs and spec endpoints

	options: {

		definition: {
			openapi: '3.0.0',
			info: {
				title: 'Application with swagger docs',
				version: '1.0.0',
				description: 'My application with swagger docs'
			}
		},

		apis: [
			'app/**/*.ts',
			'docs/paths/**/*.yml',
			'start/routes.ts'
		],
		basePath: '/'
	},
} as SwaggerConfig

```

and here is a screenshot of the redirect 
![image](https://user-images.githubusercontent.com/50522164/219350773-123ac86b-3ce5-4668-856e-2e91533440b8.png)

**Comment by VladyslavP98** [comment]
Try to open `/docs/index.html` instead of `/docs`
