### ISSUE TITLE
Running `node ace swagger:generate` fails without app env variables

### ISSUE THREAD

**Issue by fsevenm** [reg2005/adonis5-swagger#41]
## Prerequisites

Running `node ace swagger:generate` fails without env variables. The case where we build it in the ci/cd, it's not good to put the app envs there. Furthermore, the `node ace build` itself can be run successfully without the env variables.

![image](https://user-images.githubusercontent.com/29963765/222309452-4af00c7d-8cf7-4a0b-a77b-47396e0dac2e.png)

## Package version
1.4.1

## Node.js and npm version
❯ node -v
v16.19.1

❯ npm -v
8.19.3

## Sample Code (to reproduce the issue)
-

## BONUS (a sample repo to reproduce the issue)
-

**Comment by VladyslavP98** [comment]
CLI is built on top of adonis ace, this is not package issue. You can disable validation in `env.ts` file
