### ISSUE TITLE
Edit layout setting

### ISSUE THREAD

**Issue by antt0n** [reg2005/adonis5-swagger#7]
Hello,
SwaggerUI has the [layout option](https://github.com/swagger-api/swagger-ui/issues/3229) to remove the topbar from the UI.
Is it possible to implement this option?

**Comment by VladyslavP98** [comment]
You could install adonis views and render view with swagger ui. For example:
```html
<head>
<script src="https://unpkg.com/swagger-ui-dist@3/swagger-ui-bundle.js" charset="UTF-8"></script>
<script>
const ui = SwaggerUIBundle({
    url: {{ linkToSwaggerJson}} // args for view,
    dom_id: '#swagger-ui',
    presets: [
      SwaggerUIBundle.presets.apis,
      SwaggerUIBundle.SwaggerUIStandalonePreset
    ],
    layout: "StandaloneLayout"
  })
</script>
</head>
<body>
<div id="swagger-ui"></div> 
</body>
```



Our package uses already bundled ui, so we can't configure ui. I could add this functionality to package. Do you need it ?

**Comment by antt0n** [comment]
Oh, okay, I get it!
I think this feature would be very interesting, because it's the only one that's more or less missing to make the module fully implemented for Adonis.
I was also wondering why not make a wiki that allows in a few sentences to understand how it's possible to set up Swagger directly.
Thank you!

**Comment by VladyslavP98** [comment]
We added info how to configure custom swagger-ui to readme.md
