### ISSUE TITLE
Make the Swagger docs available when building for production

### ISSUE THREAD

**Issue by daniel-walz** [reg2005/adonis5-swagger#8]
## Why this feature is required (specific use-cases will be appreciated)?
When building the AdonisJS application (for production), the docs folder or the Swagger comments in the controllers/models are not included in the build folder. This then leads to the Swagger UI not showing any endpoint info when running in production.
I'm not sure if I have missed something on how to get this "out of the box" when doing a production build.

## Have you tried any other work arounds?
The workaround for me has currently been to manually copy the docs folder to the build folder after the build step has completed.
Not sure if there is a workaround when adding the Swagger comments in the controllers/models? It seems like the comments get stripped out in the build step.

## Are you willing to work on it with little guidance?
I currently don't have that much free time.

**Comment by VladyslavP98** [comment]
Yes, typescript really drop your comments from js files. Default adonis ts preset contains option `removeComments=true`. You should set for false for fix it.
But I use swagger with my ts files. Do you have ts files on your server ? Package should resolve path to you ts files, if build dir is inside directory with your typescript files. Could you demonstrate your file system content ? What does package version do you use?

**Comment by daniel-walz** [comment]
I have a fairly basic AdonisJS 5 app, here you can see the folder structure:
![image](https://user-images.githubusercontent.com/75848320/106604210-9e799a00-655f-11eb-8a29-95270b8dd64c.png)

As you can see I have a docs/swagger folder with the settings.yml as well, when I remove the yaml file I don't get any endpoints in my Swagger UI, even if I have Swagger comments in the controller.

I think the files on the server in the build folder are .js files without any comments, I have not changed the `removeComments` flag, maybe need to try that, but then I think I prefere to have the Swagger docs separatly in the docs folder instead. But that still needs to be moved manually to the build folder.

When we deploy to production we only take the /build folder and the node_modules folder, so we skip all the source files, I assume that is why it can't find the comments in the non-existing .ts files.

**Comment by VladyslavP98** [comment]
> When we deploy to production we only take the /build folder and the node_modules folder, so we skip all the source files, I assume that is why it can't find the comments in the non-existing .ts files.

This package expects that you have .ts files on your server.  
I will think how to copy swagger files during your build, maybe adonis has hooks for production build.

**Comment by daniel-walz** [comment]
Yes, then I guess I have to look into that or just keep our copy step for the docs folder. But then I know what this package supports.

**Comment by daniel-walz** [comment]
Yes, then I guess I have to look into that or just keep our copy step for the docs folder. But then I know what this package supports.

**Comment by VladyslavP98** [comment]
> Yes, then I guess I have to look into that or just keep our copy step for the docs folder. But then I know what this package supports.

https://github.com/reg2005/adonis5-swagger/pull/10
I developed production mode for swagger. We will publish new features as soon as tested on our projects.


Could you add `"adonis5-swagger": "git://github.com/reg2005/adonis5-swagger.git#swagger_mode"` to your `package.json` and check is this feature solves your problems ?

**Comment by daniel-walz** [comment]
I added it like this:

```
"dependencies": {
    "@adonisjs/core": "^5.0.4-preview-rc-2.1",
    "@adonisjs/lucid": "^10.0.0",
    "@adonisjs/repl": "^1.1.6",
    "luxon": "^1.25.0",
    "proxy-addr": "^2.0.6",
    "reflect-metadata": "^0.1.13",
    "source-map-support": "^0.5.19",
    "adonis5-swagger": "git://github.com/reg2005/adonis5-swagger.git#swagger_mode"
  }
```

npm install:

```
> npm install
npm WARN @apidevtools/swagger-parser@10.0.2 requires a peer of openapi-types@>=7 but none is installed. You must install peer dependencies yourself.
npm WARN The package reflect-metadata is included as both a dev and production dependency.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.3.1 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.3.1: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

added 780 packages from 421 contributors and audited 783 packages in 44.656s
```

Build info:

```
> node ace build --production

[ info ]  cleaning up "./build" directory
[ info ]  compiling typescript source files
[ error ]  typescript compiler errors
error TS2688: Cannot find type definition file for 'adonis5-swagger'.
config/swagger.ts:1:31 - error TS2307: Cannot find module '@ioc:Adonis/Addons/Swagger' or its corresponding type declarations.

1 import { SwaggerConfig } from '@ioc:Adonis/Addons/Swagger'
```

But when I try to start the app after building it I get this:

```
> node server.js

Error: Cannot find module '/app/node_modules/adonis5-swagger/build/index.js'. Please verify that the package.json has a valid "main" entry
    at tryPackage (internal/modules/cjs/loader.js:322:19)
    at Function.Module._findPath (internal/modules/cjs/loader.js:683:18)
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:1007:27)
    at resolveFileName (/app/node_modules/resolve-from/index.js:29:39)
    at resolveFrom (/app/node_modules/resolve-from/index.js:43:9)
    at Object.module.exports [as default] (/app/node_modules/resolve-from/index.js:46:47)
    at Object.resolveFrom (/app/node_modules/@poppinss/utils/build/src/resolveFrom.js:25:34)
    at Registrar.loadProvider (/app/node_modules/@adonisjs/fold/build/src/Registrar/index.js:49:23)
    at /app/node_modules/@adonisjs/fold/build/src/Registrar/index.js:67:53
    at Array.forEach (<anonymous>)
```

**Comment by daniel-walz** [comment]
Btw, will it be enough to have this in the apis property in the Swagger config options?

```
apis: [
  'docs/swagger/**/*.yml'
]
```

**Comment by VladyslavP98** [comment]
> I added it like this:
> 
> ```
> "dependencies": {
>     "@adonisjs/core": "^5.0.4-preview-rc-2.1",
>     "@adonisjs/lucid": "^10.0.0",
>     "@adonisjs/repl": "^1.1.6",
>     "luxon": "^1.25.0",
>     "proxy-addr": "^2.0.6",
>     "reflect-metadata": "^0.1.13",
>     "source-map-support": "^0.5.19",
>     "adonis5-swagger": "git://github.com/reg2005/adonis5-swagger.git#swagger_mode"
>   }
> ```
> 
> Build info:
> 
> ```
> > node ace build --production
> 
> [ info ]  cleaning up "./build" directory
> [ info ]  compiling typescript source files
> [ error ]  typescript compiler errors
> error TS2688: Cannot find type definition file for 'adonis5-swagger'.
> config/swagger.ts:1:31 - error TS2307: Cannot find module '@ioc:Adonis/Addons/Swagger' or its corresponding type declarations.
> 
> 1 import { SwaggerConfig } from '@ioc:Adonis/Addons/Swagger'
> ```
> 
> But when I try to start the app after building it I get this:
> 
> ```
> > node server.js
> 
> Error: Cannot find module '/app/node_modules/adonis5-swagger/build/index.js'. Please verify that the package.json has a valid "main" entry
>     at tryPackage (internal/modules/cjs/loader.js:322:19)
>     at Function.Module._findPath (internal/modules/cjs/loader.js:683:18)
>     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:1007:27)
>     at resolveFileName (/app/node_modules/resolve-from/index.js:29:39)
>     at resolveFrom (/app/node_modules/resolve-from/index.js:43:9)
>     at Object.module.exports [as default] (/app/node_modules/resolve-from/index.js:46:47)
>     at Object.resolveFrom (/app/node_modules/@poppinss/utils/build/src/resolveFrom.js:25:34)
>     at Registrar.loadProvider (/app/node_modules/@adonisjs/fold/build/src/Registrar/index.js:49:23)
>     at /app/node_modules/@adonisjs/fold/build/src/Registrar/index.js:67:53
>     at Array.forEach (<anonymous>)
> ```

Try to install in next way:

1. Add to package json
2. Run `npm i`
3. Run `node ace invoke adonis5-swagger`

**Comment by daniel-walz** [comment]
This is what happens then:

```
$ node ace invoke adonis5-swagger
UPDATE: .adonisrc.json { commands += "adonis5-swagger/build/commands" }
UPDATE: .adonisrc.json { providers += "adonis5-swagger" }
(node:39272) UnhandledPromiseRejectionWarning: Error: Template file not found: C:\Repositories\GitHub\setting-service\node_modules\adonis5-swagger\build\templates\config.txt
    at read (C:\Repositories\GitHub\setting-service\node_modules\smpltmpl\index.js:21:10)
    at templateFromFile (C:\Repositories\GitHub\setting-service\node_modules\smpltmpl\index.js:80:15)
    at Object.apply (C:\Repositories\GitHub\setting-service\node_modules\mrm-core\src\formats\template.js:33:14)
    at TemplateLiteralFile.apply (C:\Repositories\GitHub\setting-service\node_modules\@adonisjs\sink\src\Files\Formats\TemplateLiteral.js:43:26)
    at TemplatesManager.copyTemplateFor (C:\Repositories\GitHub\setting-service\node_modules\@adonisjs\sink\src\Tasks\TemplatesManager\index.js:98:18)
    at C:\Repositories\GitHub\setting-service\node_modules\@adonisjs\sink\src\Tasks\TemplatesManager\index.js:114:41
    at Array.forEach (<anonymous>)
    at TemplatesManager.copyTemplatesFor (C:\Repositories\GitHub\setting-service\node_modules\@adonisjs\sink\src\Tasks\TemplatesManager\index.js:114:14)
    at C:\Repositories\GitHub\setting-service\node_modules\@adonisjs\sink\src\Tasks\TemplatesManager\index.js:132:18
    at Array.forEach (<anonymous>)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:39272) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which
was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejecti
ons_mode). (rejection id: 1)
(node:39272) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit c
ode.
CREATE: ace-manifest.json file
```

**Comment by VladyslavP98** [comment]
Try remove your node_modules and reinstall dependencies. And please check, is `\node_modules\adonis5-swagger\build\templates\config.txt` exist

**Comment by daniel-walz** [comment]
I did remove and re-install the node modules, I still get the same error. This is the contents of my adonis5-swagger/build folder:

```
adonis-typings/
commands/
providers/
src/
index.d.ts
index.js
```

**Comment by VladyslavP98** [comment]
We published package to npm. Could you reinstall package as usual npm package and check ?

**Comment by daniel-walz** [comment]
Now I have tried it, it works when I do a production build locally and start the app from the /build folder. 
When I run it in "production" it is the same problem, I still need to copy the /docs folder manually.

From what I can see it does not create/generate any Swagger docs resource in the /build folder.
So where does it fetch the Swagger docs in this new release when building for production? 

This is the version I tried:

`"adonis5-swagger": "^1.2.1",`

**Comment by VladyslavP98** [comment]
We recommend add post hook for build: https://github.com/reg2005/adonis5-swagger#production-using

It is easiest way for solving this problem

**Comment by daniel-walz** [comment]
There are some confusing things in the docs here regarding the setup for production.

When I check my config/swagger.ts file which was generated when invoking adonis5-swagger I can't see the same structure as your example.
```
import { SwaggerConfig } from '@ioc:Adonis/Addons/Swagger'

export default {
	uiEnabled: true, //disable or enable swaggerUi route
	uiUrl: 'docs', // url path to swaggerUI
	specEnabled: true, //disable or enable swagger.json route
	specUrl: '/swagger.json',
        ....
```
Your example:
```
const swaggerConfig = { 
	mode: process.env.NODE_ENV === 'production' ? 'PRODUCTION' : 'RUNTIME',
	specFilePath: 'docs/swagger.json'
}
```

I would assume I just add it like so:
```
import { SwaggerConfig } from '@ioc:Adonis/Addons/Swagger'

export default {
	mode: process.env.NODE_ENV === 'production' ? 'PRODUCTION' : 'RUNTIME',
	uiEnabled: true, //disable or enable swaggerUi route
	uiUrl: 'docs', // url path to swaggerUI
	specEnabled: true, //disable or enable swagger.json route
	specUrl: '/swagger.json',
	specFilePath: 'docs/swagger.json',
        ...
```

But then my next question is why you are using process.env here? In Adonis 5 they use the Env module in the [docs](https://preview.adonisjs.com/guides/environment-variables).
```
import Env from '@ioc:Adonis/Core/Env'

Env.get('NODE_ENV')

// with default value
Env.get('NODE_ENV', 'development')
```

And the last question then is, when you add your post build hook, you copy the whole /docs folder, that in my case contains the swagger yml files, do I then really need the generated json file?

**Comment by VladyslavP98** [comment]
Sorry for the late response.

> And the last question then is, when you add your post build hook, you copy the whole /docs folder, that in my case contains the swagger yml files, do I then really need the generated json file?

You need to copy only swagger spec json. This file was generated by swagger-jsdoc and consists of all schemes for swagger.

> But then my next question is why you are using process.env here? In Adonis 5 they use the Env module in the docs.

Of course you can use adonis env for getting access to your env variables. For this case there is no differences.

> When I check my config/swagger.ts file which was generated when invoking adonis5-swagger I can't see the same structure as your example.

New options for swagger config was added in last version. Maybe your config file was generated by previous version. I will check options for rewriting config in adonis during provider installation.

Can I close issue ? Do you have additional questions ?

**Comment by daniel-walz** [comment]
You can close it, thanks for the help.
